Category.create(name: 'Drama');
Category.create(name: 'Cartoon');
Category.create(name: 'Novel');
Category.create(name: 'History');
Category.create(name: 'Journal');
Category.create(name: 'Children');
Category.create(name: 'Art');
Category.create(name: 'Health');
Category.create(name: 'Travel');
Category.create(name: 'Cookbook');
Category.create(name: 'Guide');
Category.create(name: 'Horror');
Category.create(name: 'Science');
Category.create(name: 'Other');
User.create!(name:  "Admin",
             email: "admin@emall.com",
             password:              "passwordemall",
             password_confirmation: "passwordemall",
             admin: true);
User.create!(name:  "Jack",
             email: "myemail@123.com",
             password:              "abcd1234",
             password_confirmation: "abcd1234");
User.create!(name:  "Cyril",
             email: "youremail@123.com",
             password:              "abcd1234",
             password_confirmation: "abcd1234");
